/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bitmap.transformer;

import org.junit.Test;
import static org.junit.Assert.*;
import bitmap.transformer.Bitmap.*;

import java.io.File;
import java.io.IOException;

public class AppTest {
    String pathToFile = "src/main/resources/mario.bmp";
    @Test
    public void testRandomize() throws IOException {
        File file = new File(pathToFile);
        Bitmap bitmap = new Bitmap(file);
    }
}
